### ISSUE TITLE
'character_ranks.json' property request

### ISSUE THREAD

**Issue by Ird3s** [Mar-7th/StarRailRes#10]
Hi, would it be possible to include the 'Param' properties from Dimbreath's AvatarRankConfig.json in your own 'character_ranks' file?

Thanks in advance

**Comment by mobyw** [comment]
`Param` in `AvatarRankConfig.json` is just used to render description string, do you need it for calculation?

**Comment by Ird3s** [comment]
Correct. Should I be looking elsewhere then?

**Comment by mobyw** [comment]
Are you making applications such as simulated combat? `Param` cannot represent the property name corresponding to the value. Manual data labeling can take a long time.

**Comment by mobyw** [comment]
In game processing, values are taken directly in order, not based on names.

**Comment by Ird3s** [comment]
Yeah I saw it doesn't have the corresponding type attached to the values, but i can't find anything better either. 
Would you recommend gathering the data and manually label it instead, then? Or is there another way?

**Comment by mobyw** [comment]
The relevant configs are in `Avatar_{VOTag}_00_Config` & `Avatar_{VOTag}_00_Ability`. Parameters will be assigned to `DynamicHashes` in order.

**Comment by mobyw** [comment]
Of course parsing these files also requires a period of research.

**Comment by Ird3s** [comment]
Thanks, I guess I'll look into those, though as you say it will require research time...

**Comment by Ird3s** [comment]
Oh, what about relic sets conditionals? Do you know where those are stored?

**Comment by mobyw** [comment]
Similar structure to characters, in `RelicAbility`

**Comment by Ird3s** [comment]
I see, thanks a lot

**Comment by Scrubles** [comment]
Hey @Ird3s, did you ever find the connection between the params and the abilities? It seems there's a trigger on the ability json, it has the property, but I didn't find a connection from the DynamicHashes to the params.

Also @mobyw, thanks for the data. Sorry for sending a msg on a closed issure. Is it possible to share the script used to generate the jsons?

**Comment by mobyw** [comment]
Hi @Scrubles, `DynamicValues` with `ReadInfo` are bind to these params, e.g.
```json   
"ReadInfo": {
  "Type": "None",
  "Str": "Rank01"
}
```
will be bind to first params of rank1.

It's not easy to parse because the modifiers are applied at different times and in different orders.
If you are interested in this, I can open a related discussion thread.

For repo generating scripts, I will upload scripts that can be fully automatically parsed to this repo in the next version update.
