### ISSUE TITLE
Aventurine's Skill Icons are Wrong

### ISSUE THREAD

**Issue by seriaati** [Mar-7th/StarRailRes#14]
# In StarRailRes
This is `/icon/skill/1304_skill.png`
![skill](https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/skill/1304_skill.png)
This is `/icon/skill/1304_ultimate.png`
![ultimate](https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/skill/1304_ultimate.png)
This is wrong, it should be the other way around.
# In Honkai Star Rail Wiki
![image](https://github.com/Mar-7th/StarRailRes/assets/61446626/11ff05cf-6ad6-45ca-94f4-40a474a8290c)
# In Mihomo API
This also causes the API to return the wrong icons:
```json
{
      "id": "130402",
      "name": "繁荣基石",
      "level": 9,
      "max_level": 15,
      "type": "BPSkill",
      "type_text": "战技",
      "effect": "Defence",
      "effect_text": "防御",
      "icon": "icon/skill/1304_skill.png"
},
{
      "id": "130403",
      "name": "轮盘勋爵",
      "level": 5,
      "max_level": 15,
      "type": "Ultra",
      "type_text": "终结技",
      "effect": "SingleAttack",
      "effect_text": "单攻",
      "icon": "icon/skill/1304_ultimate.png"
}
```

**Comment by mobyw** [comment]
Fixed now
