### ISSUE TITLE
8006.png is missing

### ISSUE THREAD

**Issue by alvisukasusu** [Mar-7th/StarRailRes#16]
Mar-7th/StarRailRes/blob/master/icon/character/
![image](https://github.com/Mar-7th/StarRailRes/assets/167173617/83ced6b7-9e12-4af8-b21f-264833c10c96)

**Comment by NatHacks** [comment]
![Capture d’écran 2024-05-09 à 14 14 51](https://github.com/Mar-7th/StarRailRes/assets/62850359/29c69355-d19d-483c-967c-9564517ad79b)

**Comment by mobyw** [comment]
should be correct now
