### ISSUE TITLE
Mixed up relics with API

### ISSUE THREAD

**Issue by ShalltearFR** [Mar-7th/StarRailRes#17]
Hello,

I have a small issue regarding the API, it can randomly happen that relics get mixed up.
Usually, the order is as follows:
- Helmet
- Gloves
- Chest
- Boots
- Orb
- Link rope

But sometimes I might have this order, for example:
- Gloves
- Chest
- Boots
- Orb
- Link rope
- Helmet

The order is relatively important to me because it completely disrupts a build analysis I'm doing on the site.
Would it be possible to add a property of helmet, gloves, chest, boots, orb, cord to the equipped piece? Detecting the glove and helmet property would be easy as the main stats never change.

The rendering on the site :
![image](https://github.com/Mar-7th/StarRailRes/assets/20574430/39cdbe4e-1089-4e99-ad20-278e09ba15c4)

**Comment by mobyw** [comment]
Is the unsorted data fetched from the API or locally cached? I don't seem to have seen the helmet in the last item.

**Comment by ShalltearFR** [comment]
The data can arrive in a disorderly manner when, for example, a player does not fully equip themselves, leaving, for instance, the boots and rope slots empty. 
After waiting 20 minutes, equipping the boots and rope will cause the disorder, and these boots and rope will display at the end of the list. 
However, I have noted that after a few days, the order restores itself. 

The only solution I have found is to ask the person to completely unequip, wait a bit, and then fully re-equip without leaving any empty slots.

**Comment by mobyw** [comment]
Hi, the new fields have been added in recent updates, please refer to changelog in discord server.

https://march7th.xyz/en/api/

**Comment by ShalltearFR** [comment]
Thank you very much, fast and efficient 👌
