### ISSUE TITLE
Use of 'p' instead of 'i' to indicate percentage values

### ISSUE THREAD

**Issue by Riktam-Santra** [Mar-7th/StarRailRes#3]
All data parameters as of right now are indicated by a `#1[i]` for an integer value or a `#1[f]` value for indicating floating point placeholders of parameters. However this causes problems as even percentage values are indicated as `#1[i]` which indicates it to be an integer.

My suggestion is to use the character 'p' to indicated percentage values for example

`Deals Ice DMG equal to #1[i]% of March 7th's ATK to a single enemy.`
The placeholder `#1[i]` here indicates it's an **integer** even though it is actually a **percentage** value. This can be replaced with a 'p' to indicated this is a percentage value.

`Deals Ice DMG equal to #1[p]% of March 7th's ATK to a single enemy.`

Note: I do understand that this can be achieved by using Regex as each placeholder ends with a `%` if it is a percentage values, but having it indicated in the data itself would save a lot of computation power.

**Comment by mobyw** [comment]
Since the param values are just used for filling string template, would it be better to directly set the param list to the corresponding string form?

`Deals Ice DMG equal to #1 of March 7th's ATK to a single enemy.`

`params: [ "10%" ]`

If it is modified like this, there will be no need to parse different formats, only need a simple string replacement.

**Comment by Riktam-Santra** [comment]
That would be a choice but that will again limit any parameter calculation if anyone would like to.

For example if i need to calculate how much percentage hike am i getting from one level to another, i would have to again parse the parameters from a string and the string can have a change of having a `%` in the end.

**Comment by gertasik** [comment]
Strongly disagree with this. The `#1[i]` notation for percentage is what the game itself uses in the TextMap files, so changing this to some other arbitrary value would just introduce a double standard.

The point of this suggestion was to add clarity, but I feel that it would have the exact opposite effect.

**Comment by mobyw** [comment]
I forgot an important point just now, the value given by the param list is the exact value, and the displayed value is rounded off, so it seems that it is not advisable to directly parse it into the display format.

The original placeholder `#1[f1]` will be replaced by `3.2` if the param value is `3.25` and `#1[f1]%` will be replaced by `3.2%` if the param value is `0.0325`. For the percentage form that retains decimals, how should it be re-expressed reasonably?

**Comment by mobyw** [comment]
> Strongly disagree with this. The `#1[i]` notation for percentage is what the game itself uses in the TextMap files, so changing this to some other arbitrary value would just introduce a double standard.
> 
> The point of this suggestion was to add clarity, but I feel that it would have the exact opposite effect.

The repo directly uses the same expression as the game config now. If it does not bring about obvious efficiency improvements, it is not inclined to modify this expression.

**Comment by Riktam-Santra** [comment]
>The repo directly uses the same expression as the game config now. If it does not bring about obvious efficiency improvements, it is not inclined to modify this expression.

Apologies, I didn't know this was actual game from the game config itself, I thought maybe it was a more custom formatted data.

If the data is extracted directly from the game config it will only introduce more problems to change anything in the data, I'll close the request, it will be better to just keep it like this then.
