### ISSUE TITLE
relic rarity icons

### ISSUE THREAD

**Issue by metalcupcake5** [Mar-7th/StarRailRes#6]
![image](https://github.com/Mar-7th/StarRailRes/assets/43897385/e1315027-3905-4e31-adf9-9628f453a1d6)
i cant seem to find the relic rarity indicators that appear on the relic display, would it be possible to add them? (example is the orange circle in the above image)

**Comment by mobyw** [comment]
do you mean the icon in front of the relic level?

i think it is most likely to use a circle image as the background, superimpose a solid circle, and then fill it with color (most of the decorative icons are stored as white images, and the colors are superimposed when rendering).

**Comment by metalcupcake5** [comment]
> do you mean the icon in front of the relic level?

yes i do

> i think it is most likely to use a circle image as the background, superimpose a solid circle, and then fill it with color (most of the decorative icons are stored as white images, and the colors are superimposed when rendering).

was hoping they'd be premade so i could do less work but ig not 3:, will try to use this method to do it manually
