### ISSUE TITLE
Add level requirement in characters traces

### ISSUE THREAD

**Issue by VDRBreno** [Mar-7th/StarRailRes#9]
Some traces need an specific level to unlock, is possible to add some property to refer that?

Example: skill tree 1002210 from Dan Heng, need the character have level 80 to unlock.

I didn't check all the skills, but in this case, the property "promotion" in "levels" at first index has value 0.

**Comment by mobyw** [comment]
> Some traces need an specific level to unlock, is possible to add some property to refer that?

Whether a point is unlocked or not is determined based on the character’s promotion and whether the pre-points are unlocked. 

> Example: skill tree 1002210 from Dan Heng, need the character have level 80 to unlock.
> 
> I didn't check all the skills, but in this case, the property "promotion" in "levels" at first index has value 0.

pre_points of 1002210:

```
        "pre_points": [
            "1002208"
        ]
```

1002208:

```
"levels": [
            {
                "promotion": 6
            }
]
```

**Comment by VDRBreno** [comment]
Some traces need more than promotion 6 (70+), but looking deeper, I understood that there is a pattern in the tree of traces that are repeated when it is the same path. So I made this relationship between path and anchors.

Destruction / Warrior
Anchor: Point17 - lv.75
Anchor: Point18 - lv.80

The Hunt / Rogue
Anchor: Point17 - lv.75
Anchor: Point18 - lv.80

Erudition / Mage
Anchor: Point18 - lv.80

Harmony / Shaman
Anchor: Point17 - lv.75
Anchor: Point18 - lv.80

Nihility / Warlock
Anchor: Point17 - lv.75

Preservation / Knight
Anchor: Point17 - lv.75
Anchor: Point18 - lv.80

Abundance / Priest
Anchor: Point17 - lv.75
Anchor: Point18 - lv.80

Since it's not related to the character or any specific trait, I don't know if it's still interesting to implement.

**Comment by VDRBreno** [comment]
And while I was looking for the pattern, I saw that the skill tree 1104101 contains parameters but in the description there is no space to replace in the description like '#1[i]' or something like that.

```json
{
    "id": "1104101",
    "name": "Integrity",
    "max_level": 1,
    "desc": "Gepard has a higher chance to be attacked by enemies.",
    "params": [
        [
            3
        ]
    ],
    ...
}
```

**Comment by mobyw** [comment]
> Some traces need more than promotion 6 (70+)

This is ignored before, an additional `level` field is required to describe the level limit for unlocking

**Comment by mobyw** [comment]
> And while I was looking for the pattern, I saw that the skill tree 1104101 contains parameters but in the description there is no space to replace in the description like '#1[i]' or something like that.

The `params` field is used for both string formatting and numerical value acquisition during game operation. Just ignore the redundant ones.

Example shows increasing taunt by 300%.

**Comment by VDRBreno** [comment]
Correcting the relationship I made above, it seems that the path doesn't actually matter, but currently all anchors Point17 requires level 75 and Point18 requires level 80.

Taking this into consideration, it doesn't seem interesting to me to add a new field for this.

Thanks for the answers!
